const STRINGS = {
  statusError: {
    requestSuccess: 'Envio realizado com sucesso.',
    createSuccess: 'Criação realizada com sucesso.',
    badRequest: 'Erro na requisição',
    notFound: 'Rota não localizada',
    requestForbidden: 'Voce não tem direitos de acesso ao conteúdo.',
    methodNotAllowed: 'O método de solicitação é conhecido pelo servidor, mas foi desativado e não pode ser usado.',
    notPermission: 'Sem premissão de acesso.',
    requestTimeOut: 'Tempo de requisição esgotado.',
    internalServerError: 'Erro interno da aplicação.',
    responseError: 'Resposta inválida.',
    serviceUnavailable: 'Servidor indisponível.',
    default: 'Erro desconhecido, contato o administrador.'
  },
  ok: 'OK',
  continue: 'Continuar',
  conclude: 'Concluir',
  loading: 'Carregando...',
  yes: 'Sim',
  no: 'Não',
  cancel: 'Cancelar',
  otherRecords: 'DEMAIS REGISTROS',
  save: 'Salvar',
  volume: 'Volume',
  createdAt: 'Data de criação',
  retry: 'Tentar novamente',
  tax: 'Tarifa',
  period: 'Período',
  venue: 'Praça',
  login: {
    signIn: 'ENTRAR',
    errors: {
      fcmError: 'Erro ao obter e salvar o token de notificação.',
      signIn: 'Não foi possível realizar o seu login, tente novamente!'
    }
  },
  menu: {
    newProposal: 'Nova Proposta',
    viewProposal: 'Visualizar Proposta',
    managementReport: 'Relatório Gerencial',
    viewPrice: 'Preço Tabelado'

  },
  proposal: {
    titleHeader: 'PROPOSTAS',
    singletitleHeader: 'PROPOSTA',
    totalVolume: 'VOLUME TOTAL',
    volumeTitle: 'VOLUMES',
    port: 'PORTO',
    railroad: 'FERROVIA',
    volume: 'VOLUME',
    flow: 'FLUXOS',
    expired: 'Expirada',
    emptyFlow: 'Ainda não foram adicionados fluxos a proposta',
    typeLabel: 'TIPO DE PROPOSTA',
    startDateLabel: 'Prazo Inicial',
    endDateLabel: 'Prazo Final',
    endDateGreater: 'O prazo final precisa ser maior que o prazo inicial.',
    selectDatePrefix: 'Selecione o',
    newFlow: 'NOVO FLUXO',
    active: 'ADITIVO',
    contract: 'CONTRATO',
    sendProposal: 'ENVIAR PROPOSTA',
    filterProposal: 'Filtrar propostas',
    hallsTitle: [
      'Norte',
      'Santos',
      'Tubarão'
    ],
    tabsDetails: {
      inNegotiation: 'Em negociação',
      conclude: 'Concluídas',
      refused: 'Recusadas'
    },
    share: {
      reportTitle: 'Gerar o PDF',
      title: 'Exportar lista de proposta',
      itemsShare: {
        negotiation: 'Em Negociação',
        conclude: 'Concluído'
      }
    },
    errors: {
      failedToAccept: 'Erro ao aceitar proposta, por favor, tente mais tarde.',
      failedToRestore: 'Erro ao restaurar proposta, por favor, tente mais tarde.',
      failedToRefuse: 'Erro ao recusar proposta. Por favor, tente mais tarde.'
    },
    successfullModal: {
      title: 'Proposta enviada!',
      message: 'Sua negociação foi aberta, em breve você terá retorno da VL!',
      acceptedTitle: 'Proposta aceita!',
      acceptedMessage: 'Sua negociação foi fechada, em breve você terá retorno da VL!.',
      refusedTitle: 'Proposta recusada',
      refusedMessage: 'Sua negociação foi encerrada.',
      restoredTitle: 'Proposta restaurada!',
      restoredMessage: 'Sua negociação foi restaurada, em breve você terá retorno da VL!.!'
    },
    inNegociationTitle: 'PROPOSTA EM NEGOCIAÇÃO',
    acceptedTitle: 'PROPOSTA CONCLUÍDA',
    refusedTitle: 'PROPOSTA RECUSADA',
    msgAccept: 'Tem certeza que aceita essa proposta?',
    msgrefused: 'Tem certeza que irá recusar essa proposta?',
    msgrestored: 'Tem certeza que irá restaurar essa proposta?',
    sendConfirmation: 'Deseja enviar esta proposta?',
    acceptConfirmation: 'Tem certeza que aceita esta proposta?',
    refuseConfirmation: 'Tem certeza que irá recusar esta proposta?',
    restoreConfirmation: 'Tem certeza que irá restaurar esta proposta?',    
    msgError: 'Ocorreu um erro na requisição, favor tentar novamente',
    comingSoonProposalList: 'A lista de proposta está em construção e em breve estará disponível',
    emptyProposalList: 'Nenhuma proposata relacionada',
    emptyCommentsList: 'Nenhuma observação relacionada',
    newCommentTextInputPlaceholder: 'Escreva aqui a sua observação',
    sendNewComment: 'Enviar',
    invalidMessage: 'Por favor insire uma mensagem válida',
    errorList: 'Erro ao obter a lista de proposta, tente novamente mais tarde'
  },
  proposalTaxes: {
    newSale: 'NOVA VENDA',
    iss: 'ISS',
    icms: 'ICMS',
    pisCofins: 'PIS/COFINS',
    top: 'TOP',
    total: 'TOTAIS',
    tolVolume: 'Tol % Volume',
    tolTax: 'Tol % Tarifa',
    stay: 'Estadia',
    storage: 'Armazenagem',
    diesel: 'Repasse diesel',
    offshore: 'Offshore',
    errors: {
      exceedVolume: 'O valor da tol. do volume deve estar entre 0 e 100',
      exceedTax: 'O valor da tol. de tarifa deve estar entre 0 e 100',
      savingSaleTitle: 'Erro ao salvar venda',
      savingSale: 'Tivemos um problema ao salvar a sua venda. Tente novamente',
      responseJsonIssue: 'Problema ao realizar a requisição. Objeto response inválido.',
      requestIssue: 'Problema ao realizar a requisição. Problema na requisição'
    },
    changeTitle: 'PREMISSAS CONTRATUAIS'
  },  
  proposalDetail: {
    newTitle: 'NOVA PROPOSTA',
    LabelNumber: 'N° DA PROPOSTA',
    createDate: 'CRIADO EM',
    updateAt: 'MODIFICADO EM',
    termStart: 'PRAZO INCIAL',
    termEnd: 'PRAZO FINAL',
    proposalType: 'TIPO DA PROPOSTA',
    typeLabel: 'Tipo de proposta',
    premiseButtom: 'PREMISSAS CONTRATUAIS',
    flow: 'FLUXOS',
    accept: 'ACEITAR',
    edit: 'EDITAR',
    restoreProposal: 'RESTAURAR PROPOSTA',
    refuse: 'RECUSAR',
    bulk: 'CORREDOR(ES)',
    status: 'STATUS',
    product: 'PRODUTO',
    origin: 'TERMINAL',
    destiny: 'DESTINO',
    originDestiny: 'TERMINAL E DESTINO',
    periodic: 'PERÍODO',
    restore: 'RESTAURAR'
  },
  newSaleDetails: {
    newSale: 'NOVA VENDA',
    hall: 'Corredor',
    origin: 'Origem',
    months: 'Meses',
    destiny: 'Destino',
    client: 'Cliente',
    microRegion: 'Microrregião',
    product: 'Produto',
    segment: 'Segmento',
    port: 'Porto',
    status: 'Status',
    scene: 'Cenário',
    parameters: 'Parâmetro',
    salesTypeLabel: 'Tipo de Venda',
    similarSaleAction: 'Deseja consultar a lista de vendas?',
    similarSaleInfo: 'Já existem vendas mapeadas com estes parâmetros.',
    consult: 'Consultar',
    proceed: 'Prosseguir',
    factory: 'Usina',
    state: 'Estado',
    statusType: {
      mapped: 'Mapeada',
      inNegociation: 'Em negociação',
      done: 'Concluída'
    },
    salesType: {
      railroad: 'Ferrovia',
      port: 'Porto'
    },
    noPermission: 'Você não possui permissão para criar vendas.',
    errors: {
      clientInvalidObject: 'Erro ao obter a lista de clientes. Objeto inválido.',
      clientRequestIssue: 'Erro ao obter a lista de clientes. Problema ao realizar a requisição.',
      hallInvalidObject: 'Erro ao obter a lista de corredores. Objeto inválido.',
      hallRequestIssue: 'Erro ao obter a lista de corredores. Problema ao realizar a requisição.',
      destinyInvalidObject: 'Erro ao obter a lista de destinos. Objeto inválido.',
      destinyRequestIssue: 'Erro ao obter a lista de destinos. Problema ao realizar a requisição.',
      originInvalidObject: 'Erro ao obter a lista de origens. Objeto inválido.',
      originRequestIssue: 'Erro ao obter a lista de origens. Problema ao realizar a requisição.',
      productsInvalidObject: 'Erro ao obter a lista de produtos. Objeto inválido.',
      productsRequestIssue: 'Erro ao obter a lista de produtos. Problema ao realizar a requisição.',
      microRegionInvalidObject: 'Erro ao obter a lista de micro regiões. Objeto inválido.',
      microRegionRequestIssue: 'Erro ao obter a lista de micro regiões. Problema ao realizar a requisição.',
      statusInvalidObject: 'Erro ao obter a lista de status. Objeto inválido.',
      statusRequestIssue: 'Erro ao obter a lista de status. Problema ao realizar a requisição.',
      sceneInvalidObject: 'Erro ao obter a lista de cenários. Objeto inválido.',
      sceneRequestIssue: 'Erro ao obter a lista de cenários. Problema ao realizar a requisição.',
      historicInvalidObject: 'Erro ao obter a lista de históricos. Objeto inválido.',
      historicRequestIssue: 'Erro ao obter a lista de históricos. Problema ao realizar a requisição.',
      stateRequestIssue: 'Erro ao obter a lista de estados. Problema ao realizar a requisição.'
    }
  },  
  saleDetail: {
    sale: 'DETALHE DA VENDA',
    product: 'PRODUTO',
    originDestiny: 'ORIGEM E DESTINO',
    status: 'STATUS',
    moveTo: 'Mover para ',
    completed: 'Concluídas',
    change: 'Alterar ',
    info: 'Status',
    cofirmDeleteSale: 'Deseja realmente excluir esta venda?',
    successDeleteSale: 'Venda excluida com sucesso.',
    deleteYearModal: 'Você deseja excluir todas as microrregiões associadas a esse ano?',
    saveSale: 'Salvar',
    selectAllStatus: 'todos os Status',
    error: 'Erro ao salvar as alterações da venda.',
    viewContractPremisesButtonLabel: 'PREMISSAS CONTRATUAIS',
    removeMonthMessage: 'Tem certeza que deseja remover esse mês? Isso excluirá todas as microregiões que o compõem.'
  },
  price: {
    title: 'Consultar preço tabelado',
    titleList: 'Preço Tabelado',
    consult: 'consultar',
    terminal: 'Terminal',
    terminals: 'Terminais',
    hall: 'Corredor',
    halls: 'Corredores',
    city: 'Cidade',
    venue: 'Praças',
    product: 'Produto',
    products: 'Produtos'
  },
  priceFilter: {
    filterSales: 'FILTRAR VENDAS',
    apply: 'Aplicar',
    applyFilter: 'Aplicar Filtros',
    all: 'Todos',
    selectAll: 'Selecionar Todos',
    empty: 'Selecione',
    monthsSelected: 'Mêses selecionados'
  },
  tabulatedPrice: {
    title: 'CONSULTAR PREÇO TABELADO',
    result: 'PREÇO TABELADO',
    terminal: 'Terminal',
    hall: 'Corredor',
    city: 'Cidade',
    venue: 'Praça',
    product: 'Produto',
    consult: 'CONSULTAR',
    viewCity: 'VER CIDADES',
    q1: '1Q',
    q2: '2Q',
    average: 'MÉDIA',
    viewCityTitle: 'CIDADES DA PRAÇA',
    notFound: 'Nenhum resultado encontrado'
  },
  proposalForm: {
    viewContractPremisesButtonLabel: 'Premissas contratuais'
  },
  proposalAPI: {
    proposalPutFailure: 'Erro ao alterar o status da proposata. Tente novamente mais tarde.',
    proposalPutError: 'Os dados estão incorretos',
    sendProposalError: 'Erro ao enviar suas alterações.'
  },
  selectListModal: {
    searchByName: 'Pesquisar pelo nome'
  },
  flow: {
    newFlow: 'NOVO FLUXO',
    showFlow: 'DETALHES DO FLUXO',
    showVolume: 'VOLUMES EM ',
    newFlowBackValidation: 'Ao voltar você irá perder todos os dados preenchidos. Voltar mesmo assim?',
    newFlowTabInfo: 'Ao trocar de aba você irá perder todos os dados preenchidos. Trocar mesmo assim?',
    editFlow: 'EDITAR FLUXO',
    save: 'SALVAR',
    saveNew: 'SALVAR E ADICIONAR NOVO',
    railroad: 'Ferrovia',
    port: 'Porto',
    edited: 'Alterado',
    month: {
      addVolume: 'ADICIONAR VOLUME',
      addVenue: 'ADICIONAR PRAÇA',
      addTax: 'ADICIONAR TARIFA'
    },
    totalVolume: 'VOLUME TOTAL',
    monthBackValidation: 'Você inseriu dados que não foram salvos e serão perdidos. Voltar mesmo assim?',
    volumes: 'VOLUMES',
    volume: 'VOLUME',
    emptyVolumes: 'Você ainda não selecionou os meses para incluir novas praças e volumes.',
    confirmMonthRemove: 'Deseja remover o mês?',
    terminal: 'Terminal',
    terminalDestiny: 'TERMINAL E DESTINO',
    modalPort: 'O destino selecionado é um Porto VL!. Deseja criar um fluxo portuário?',
    flow: 'FLUXO',
    period: 'PERÍODO',
    product: 'PRODUTO',
    added: 'Novo',
    deleteVenue: 'Tem certeza que quer excluir esta praça?',
    deleteFlow: 'Tem certeza que quer excluir este fluxo?'    
  },
  comments: {
    errorComments: 'Erro ao recuperar as observações. Tente mais tarde novamente.',
    title: 'Observações da proposta',
    newObs: 'Nova Observação',
    noRecord: 'NENHUMA NOTIFICAÇÃO ENCONTRADA!',
    newNotificationTextInputPlaceholder: 'Escreva aqui a sua observação',
    sendNewNotification: 'Enviar',
    invalidMessage: 'Por favor insire uma mensagem válida',
    invalidTokens: 'Token inválido'
  },
  notifications: {
    title: 'OBSERVAÇÕES'
  },
  concluding: {
    acceptProposal: 'Proposta aceita!',
    refusedProposal: 'Proposta recusada!',
    acceptText: 'Sua negociação foi fechada e em breve você terá retorno da VL!',
    refusedText: 'Sua negociação foi encerrada e em breve você poderá ter retorno da VL!',
    textButtom: 'CONCLUIR',
    railRoadVolume: 'VOLUME',
    portVolume: 'VOLUME PORTO',
    labelNumber: 'Nº DA PROPOSTA',
    createDate: 'DATA DE CRIAÇÃO',
    termStart: 'PRAZO INICIAL',
    termEnd: 'PRAZO FINAL'
  },
  flowMonth: {
    newSale: 'NOVA VENDA',
    hall: 'Corredor',
    origin: 'Origem',
    months: 'Mês(es)',
    destiny: 'Destino',
    client: 'Cliente',
    product: 'Produto',
    port: 'Porto',
    status: 'Status',
    factory: 'Usina',
    salesType: {
      railroad: 'Ferrovia',
      port: 'Porto'
    },
    errors: {
      clientRequestIssue: 'Erro ao obter a lista de clientes. Problema ao realizar a requisição.',
      hallRequestIssue: 'Erro ao obter a lista de corredores. Problema ao realizar a requisição.',
      destinyRequestIssue: 'Erro ao obter a lista de destinos. Problema ao realizar a requisição.',
      originRequestIssue: 'Erro ao obter a lista de origens. Problema ao realizar a requisição.',
      productsRequestIssue: 'Erro ao obter a lista de produtos. Problema ao realizar a requisição.',
      microRegionRequestIssue: 'Erro ao obter a lista de micro regiões. Problema ao realizar a requisição.',
      statusRequestIssue: 'Erro ao obter a lista de status. Problema ao realizar a requisição.',
      sceneRequestIssue: 'Erro ao obter a lista de cenários. Problema ao realizar a requisição.',
      historicRequestIssue: 'Erro ao obter a lista de históricos. Problema ao realizar a requisição.',
      cityRequestIssue: 'Erro ao obter a lista de cidades. Problema ao realizar a requisição.',
      priceRequestIssue: 'Erro ao consultar o preço tabelado. Problema ao realizar a requisição.'
    }
  }
};

export default STRINGS;